#!/bin/bash

# Default files to ignore
# Files we don't want to upload to remote server
ignoreArray=('*.swp' '.ziployignore' '*.git*' 'ziploy' 'node_modules/*')


# Ziploy Ignore custom file
ignoreList='.ziployignore'

# Ziploy file name, without extension
zipFilename='_ziploy.zip'

ziployId="${1}"
ziploySecret="${2}"
ziployEndpoint=$(echo "$3" | xargs)
ziployEndpoint="${ziployEndpoint%/}/wp-json/ziploy/v1/update"


# Remove zipped file if alreay exists
if [[ -f $zipFilename ]]; then
    rm -rf "${zipFilename}"
    echo "Cleaning repository cache"
    sleep 1
fi

if [[ -f "$ignoreList" ]]; then
    
    echo "Generating ignore list"
    sleep 1
    
    while IFS= read -r line || [[ -n "$line" ]]; do
        
        # Trim whitespace from both ends
        line=$(echo "$line" | xargs)
        
        # Skip empty lines and lines starting with a comment (#)
        [[ -z "$line" || "$line" == \#* ]] && continue
        
        # Append '*' if line ends with '/'
        if [[ "$line" == */ ]]; then
            line="${line}*"
        fi
        
        # Append to ignore list
        ignoreArray+=("$line")

    done < "$ignoreList"
fi

# Zip everything
echo "Creating ziploy"
sleep 1
zip -qq -r "${zipFilename}" . -x "${ignoreArray[@]}"


# CURL POST zipped file to WordPress Ziploy endpoint
if [[ -f $zipFilename ]]; then

    echo "Ziploying files to remote server"

    response=$(curl -L -X POST "${ziployEndpoint}" \
        -H "cache-control: no-cache" \
        -F "ziploy=@${zipFilename}" \
        -F "id=${ziployId}" \
        -F "secret=${ziploySecret}")
    
    echo -e "\033[0;32mRemote\033[0m: $response"
    sleep 1
fi


# Remove zipped file if alreay exists
if [[ -f $zipFilename ]]; then
    rm -rf "${zipFilename}"
    echo "Cleanup completed"
    sleep 1

    echo "All tasks completed"
fi