#!/bin/bash

# Default files to ignore
# Files we don't want to upload to remote server
ignoreArray=('*.swp' '.ziployignore' '*.git*' 'ziploy' 'node_modules/\*')


# Ziploy Ignore custom file
ignoreList='.ziployignore'

# Ziploy file name, without extension
zipFilename='_ziploy.zip'

ziployId="${1}"
ziploySecret="${2}"
ziployEndpoint="${3}"

echo "id: $1"
echo "secret: $2"
echo "endpoint: $3"


# Remove zipped file if alreay exists
if [[ -f $zipFilename ]]; then
    rm -rf "${zipFilename}"
    echo "Cache Cleared"
    sleep 1
fi


# Read all ignored files and append them to ignoreArray
if [[ -f $ignoreList ]]; then

    echo "Generating list of files for ziployment"
    sleep 1

    # Loop trough all lines in file
    while read line
    do
        # Skip empty lines and lines with comment
        if [[ "$line" =~ [^[:space:]] && ${line::1} != "#" ]]; then
            ignoreArray+=("${line}")
        fi

    done < $ignoreList
fi

# Zip everything
echo "Creating ziploy"
sleep 1
zip -qq -r "${zipFilename}" . -x "${ignoreArray[@]}"


# CURL POST zipped file to WordPress Ziploy endpoint
if [[ -f $zipFilename ]]; then

    echo "Uploading files to remote server"

    response=(`curl \
        -L -X POST "${ziployEndpoint}" \
        -H "cache-control: no-cache" \
        -F "ziploy=@${zipFilename}" \
        -F "id=${ziployId}" \
        -F "secret=${ziploySecret}"`)

    echo "${response}"
fi


# Remove zipped file if alreay exists
if [[ -f $zipFilename ]]; then
    rm -rf "${zipFilename}"
    echo "Cleanup Complete"
    sleep 1
fi